# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

xcodeproj 'NFTImagePickerController Demo'
workspace '../NFTImagePickerController'
inhibit_all_warnings!

target "NFTImagePickerController Demo" do
  pod "NFTImagePickerController", :path => "../"
end

# Uncommnt the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end

